### PR TITLE
fix: remove use of `polyfill.io`

### PR DESCRIPTION
**Pull request by brenoepics**
This PR addresses the recent security concerns regarding polyfill.io, as detailed in the [Cloudflare blog](https://blog.cloudflare.com/automatically-replacing-polyfill-io-links-with-cloudflares-mirror-for-a-safer-internet) and [the hacker news](https://thehackernews.com/2024/06/over-110000-websites-affected-by.html). The domain polyfill.io was sold to a new owner, Funnull, and has been used to inject malicious JavaScript code. To mitigate this risk, I have replaced all instances of polyfill.io in [`labs-docs`](https://learning.postman.com/labs/) repo  to Cloudflare's secure mirror.

From polyfill.io original creator: https://twitter.com/triblondon/status/1761852117579427975

Issue on their repo: https://github.com/polyfillpolyfill/polyfill-service/issues/2892

### CODE REVIEW

**Review by krystian3w — APPROVED** [review]

**Comment by Daniel15** [comment]
You can completely remove these polyfills. No modern browser needs any of the polyfills that are being loaded here - IE11 was the only browser that needed them (the rest like Safari, Firefox, and Chrome have supported things like `Array.prototype.find` for nearly 10 years) and IE11 was EOL'd two years ago so it's not a concern any more.

**Comment by brenoepics** [comment]
Great, that's even better.

**Comment by tristandenyer** [comment]
Closing in favor of another PR where we swapped it for the Cloudflare version.

When we go to NextJS, this will not be used. Thank you for your contribution!

**Comment by Daniel15** [comment]
> swapped it for the Cloudflare version.

@tristandenyer  It's not actually doing anything in browsers that were released in the last 7-8 years though. All it does is slows down the page load, by having to load one more file, at a different hostname.

**Pull request closed without merging**
